# Generated by Django 3.1.2 on 2020-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_text', models.CharField(max_length=300)),
                ('post_image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
